name: Deploy

on: 
    push:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
                uses: actions/checkout@v2

            - name: Use Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '20'

            - name: Eslint
                run: npm run eslint:check

            - name: Prettier:
                run: npm run prettier:check

            - name: Test
                run: npm run test